spring:
    config:
        import: optional:file:.env[.properties]
    profiles:
        active: local

    servlet:
        multipart:
            enabled: true
            max-file-size: 50MB
            max-request-size: 50MB

server:
    port: ${PORT:8080}

# Swagger
springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui/index.html
        display-request-duration: true
        operations-sorter: method

---
# local profile
spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: ${LOCAL_DB_URL}
        username: ${LOCAL_DB_USERNAME}
        password: ${LOCAL_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            dialect: org.hibernate.dialect.MySQLDialect


logging:
    level:
        org.hibernate.type.descriptor.sql.BasicBinder: trace